drop database if exists `mspr`;

create database if not exists `mspr` default character set
utf8mb4 collate utf8mb4_unicode_ci;

use `mspr`;

CREATE TABLE `client` (
  `CODE_CLIENT` varchar(10) NOT NULL,
  `NOM` varchar(45) NOT NULL,
  `PRENOM` varchar(45) NOT NULL,
  `ADRESSE` varchar(45) NOT NULL,
  `CODE_POSTAL` char(5) NOT NULL,
  `VILLE` varchar(45) NOT NULL,
  `STIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODE_CLIENT`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `commande` (
  `ID_COMMANDE` int NOT NULL AUTO_INCREMENT,
  `CODE_CLIENT` varchar(10) NOT NULL,
  `DATE` datetime NOT NULL,
  `STIMETAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_COMMANDE`),
  KEY `FK_COMMANDE_CLIENT_idx` (`CODE_CLIENT`),
  CONSTRAINT `FK_COMMANDE_CLIENT` FOREIGN KEY (`CODE_CLIENT`) REFERENCES `client` (`CODE_CLIENT`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `produit` (
  `CODE_PRODUIT` char(10) NOT NULL,
  `LIBELLE_PRODUIT` varchar(45) NOT NULL,
  `DESCRIPTION` varchar(180) DEFAULT NULL,
  `PRIX` decimal(5,
2) NOT NULL,
  `STIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODE_PRODUIT`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `detail_commande` (
  `ID_COMMANDE` int NOT NULL,
  `CODE_PRODUIT` char(10) NOT NULL,
  `QUANTITE` int NOT NULL,
  `STIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_COMMANDE`,
`CODE_PRODUIT`),
  KEY `FK_DETAIL_COMMANDE_PRODUIT_idx` (`CODE_PRODUIT`),
  CONSTRAINT `FK_DETAIL_COMMANDE_COMMANDE` FOREIGN KEY (`ID_COMMANDE`) REFERENCES `commande` (`ID_COMMANDE`),
  CONSTRAINT `FK_DETAIL_COMMANDE_PRODUIT` FOREIGN KEY (`CODE_PRODUIT`) REFERENCES `produit` (`CODE_PRODUIT`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `role` (
  `CODE_ROLE` char(5) NOT NULL,
  `LIBELLE_ROLE` varchar(45) NOT NULL,
  `STIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CODE_ROLE`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `utilisateur` (
  `LOGIN` char(5) NOT NULL,
  `PSW` varchar(45) NOT NULL,
  `CODE_ROLE` char(5) NOT NULL,
  `STIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOGIN`),
  KEY `FK_UTILISATEUR_ROLE_idx` (`CODE_ROLE`),
  CONSTRAINT `FK_UTILISATEUR_ROLE` FOREIGN KEY (`CODE_ROLE`) REFERENCES `role` (`CODE_ROLE`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
